### ISSUE TITLE
Bug on Pxerstudio App: Reset View Port Not working 

### ISSUE THREAD

**Issue by gutzygwin** [BennyKok/PxerStudio#1]
#### Expected behavior
While using the app, its expected that when using the pxerstudio app, the Reset view port icon is meant to perform a quick reset back to default, which can be used to clear previous data or work on an ongoing project. 

#### Actual behavior
The Reset View Port Icon on the app currently doesn't perform any function when clicked on. This is supposed function on the app which allows the app to reset back to default page and is currently of no use when clicked on and doesn't function and as such can be considered as a bug.

![Screenshot_20180210-143011.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518277012/kklvll7tk7eeoujwpwjs.png)
The image above shows the position of the "Reset View Port" icon on the app interface which is currently not working. 

#### How to reproduce
• Download pxerstudio on the google playstore.
• Open the pxerstudio application. 
• Test run the Icon by sampling the interface with any drawing or project of yours.
• click on the Reset View Port as shown in the diagram above.
• Bug Found

* Browser: Pxerstudio App/ Google
* Operating system: Android 7.0

**Device Used**: Infinix Note 4

#### Recording Of The Bug

https://youtu.be/LqFiOkUd_Qg
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-pxerstudio-app-reset-view-port-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by BennyKok** [comment]
Sorry for this super late reply, but actually it will only reset your view port if you have panned or zoomed the canvas, so in the video that you are showing is actually not a bug,
