### ISSUE TITLE
Can't find export location

### ISSUE THREAD

**Issue by TheLastProject** [BennyKok/PxerStudio#11]
The app keeps telling me it succesfully exported, but I can't find the PNG files it should have saved, making me unable to share what I drew. This may just be "user error" but I looked around in my phone file manager for 5 minutes but couldn't find it.

**Comment by enxio27** [comment]
It's not just you. I tried two separate  file managers, with hidden objects visible, and I couldn't find them, either.  I couldn't even access the folder where I KNOW the saved PXER files are stored.   Need a way for the user to specify a save location, and also need some overwrite protection.

**Comment by BennyKok** [comment]
Hey, it's due to the changes of the deprecated api for getting the saving path, the files currently is saved to the internal app directory, which seems to be only visible if you browse it via the computer explorer, will have to look into it and see if can find a way to export the files somewhere else.

**Comment by TacoTheDank** [comment]
They seem to be exported to the directory `Android/data/com.benny.pxerstudio`, which most file explorers should be able to see if you are using Android 10 or lower. But yeah, this is a rather pressing issue.

**Comment by enxio27** [comment]
> They seem to be exported to the directory `Android/data/com.benny.pxerstudio`, which most file explorer apps should be able to see if you are using Android 10 or lower. But yeah, this is a rather pressing issue.

It's actually several directory levels deeper than that, and the file explorer apps can't/won't look that deeply.

**Comment by TacoTheDank** [comment]
> > They seem to be exported to the directory `Android/data/com.benny.pxerstudio`, which most file explorer apps should be able to see if you are using Android 10 or lower. But yeah, this is a rather pressing issue.
> 
> It's actually several directory levels deeper than that, and the file explorer apps can't/won't look that deeply.

Yeah I didn't mention that. I use MiXplorer (which can do pretty much anything), and it's able to access it through every level.

**Comment by TacoTheDank** [comment]
@TheLastProject This should be solved with version 1.2.0 https://github.com/BennyKok/PxerStudio/releases/tag/v1.2.0.

Big thanks to @mihajlo0743!
