### ISSUE TITLE
Crash on app launch

### ISSUE THREAD

**Issue by MTSYuki** [BennyKok/PxerStudio#7]
Just discovered this interesting app. Downloaded, installed, and when I open, the app just crashed with the messenge "Unfortunately, PxerStudio has stopped". I also permitted storage access from my app settings.

- Phone: LG K10 2017

- Model: LG-M250ds

- Android Version: 7.0

- ROM: Stock

- App Version: 1.1.1 (Installed from F-Droid)

**Comment by TacoTheDank** [comment]
Hmm... hey, could you do a little test for me? Could you install my [stack trace catching app](https://github.com/TacoTheDank/Scoop) (follow the instructions in the README to set it up) and post (or link) the crashlog? I think that would be the best way for me to be able to determine what could be causing the crash, cause it seems that this might be a Android Version specific issue.

**Comment by BennyKok** [comment]
Weird that there is another report (from play store) that it crashes on android 5.0.

**Comment by MTSYuki** [comment]
> Hmm... hey, could you do a little test for me? Could you install my [stack trace catching app](https://github.com/TacoTheDank/Scoop) (follow the instructions in the README to set it up; I'm preparing to publish it to F-Droid soon) and post (or link) the crashlog? I think that would be the best way for me to be able to determine what could be causing the crash, cause it seems that this might be a Android Version specific issue relating to styling.

Unfortunately, I don't have a PC to setup ADB and see the log.
But I'll see what I could do.

**Comment by TacoTheDank** [comment]
@MTSYuki Thanks :)

**Comment by MTSYuki** [comment]
> Weird that there is another report (from play store) that it crashes on android 5.0.

Seems like the crash is something about the old versions of Android?

Not sure what is causes, but I've haved another app (Is called "X Server", not the "X Server XSDL"), caused the same crash.

**Comment by MTSYuki** [comment]
> @MTSYuki Thanks :) The only device I have is my Android 10 Samsung Note 9, so I cannot test other Android versions easily. I'll see if I can set up some virtual devices with Android Studio to try and reproduce this crash with other Android versions, though I am quite limited by my lack of experience with virtual devices as well as laptop hard drive space.

No problem ;-)

**Comment by TacoTheDank** [comment]
@MTSYuki Can you test this APK and see if it works correctly? 
[app-debug-pxer.zip](https://github.com/BennyKok/PxerStudio/files/6290256/app-debug-pxer.zip)

**Comment by MTSYuki** [comment]
> @MTSYuki Can you test this APK and see if it works correctly? 
> [app-debug-pxer.zip](https://github.com/BennyKok/PxerStudio/files/6290256/app-debug-pxer.zip)
> 

Okay, just installed, but unfortunately, same crash occurs.

I truly appreciate your effort :-)

**Comment by TacoTheDank** [comment]
@MTSYuki I was able to get an emulator running with as close to your device's specifications as possible, and - using Scoop on the emulated device - I believe I have located and fixed the issue. Here's a test APK: [app-debug.zip](https://github.com/BennyKok/PxerStudio/files/6290546/app-debug.zip)

**Comment by MTSYuki** [comment]
> @MTSYuki I was able to get an emulator running with as close to your device's specifications as possible, and - using Scoop on the emulated device - I believe I have located and fixed the issue. Here's a test APK: [app-debug.zip](https://github.com/BennyKok/PxerStudio/files/6290546/app-debug.zip)
> 
> 

It works!!

Just tested the app right now, I maked some drawings and exported to PNG, so far works great!!

Thanks for the help!!

**Comment by TacoTheDank** [comment]
No problem! The issue specifically was that the app was declaring usage of a custom font in many places (including the splash screen text) but did not actually have it registered beforehand, so if a phone that didn't have the font built into the system (like yours, I assume because of it not being included in AOSP stock) tried to run the app, any text resource declaring this font would cause the app to crash.

@BennyKok As a heads up, issue #3 existed as I was testing on the emulated device. seems that the blurry pixel issue could still persist on some devices. @MTSYuki Were the pixels blurry on your device (as shown in the screenshot in #3)?

@MTSYuki Also, could you do one last test for me? My [Scoop](https://github.com/TacoTheDank/Scoop) app actually uses a custom font as well (but has it registered). I would like to know if my HEAD build works correctly on a device such as yours. [app-release-scoop-a723166.zip](https://github.com/BennyKok/PxerStudio/files/6290594/app-release-scoop-a723166.zip)

**Comment by MTSYuki** [comment]
> No problem! The issue specifically was that the app was declaring usage of a custom font in many places (including the splash screen text) but did not actually have it registered beforehand, so if a phone that didn't have the font built into the system (like yours, I assume because of it not being included in AOSP stock) tried to run the app, any text resource declaring this font would cause the app to crash. I have a Samsung Note 9 device, so that's why I was unable to replicate this issue on it :).

The LG UX is almost AOSP, but I have fewer fonts installed on my phone, including Roboto.

> @BennyKok As a heads up, issue #3 existed as I was testing on the emulated device. It seems that the blurry pixel issue could still persist on some devices. @MTSYuki Were the pixels blurry on your device (as shown in the screenshot in #3)?

Yeah, can confirm that also happens to me (But I thought that is normal).

@MTSYuki Also, could you do one last test for me? My Scoop app actually uses a custom font as well (but has it registered). I would like to know if my app works correctly on a device such as yours. app-release-scoop-a723166.zip (APK was built on latest commit as of this comment)

Okay, I'll try.

**Comment by MTSYuki** [comment]
Okay, so the Scoop App didn't crash when I launched it.

**Comment by TacoTheDank** [comment]
That's good. Thanks!

**Comment by BennyKok** [comment]
Thanks everyone for testing out!!
