### ISSUE TITLE
Currently Selected Colour - Bug

### ISSUE THREAD

**Issue by factorial52** [BennyKok/PxerStudio#8]
Seems like the colour selected when the app is opened becomes the colour displayed for transparency. The little circle should really change to a pattern matching the transparent background.
![Screenshot_20210409-155429](https://user-images.githubusercontent.com/79954527/114234002-260ecb00-994c-11eb-95d5-fec08d89a781.png)
![Screenshot_20210409-155445](https://user-images.githubusercontent.com/79954527/114234006-273ff800-994c-11eb-9ee6-ba8f92386ec1.png)

**Comment by TacoTheDank** [comment]
Yeah, I've noticed this bug as well. Thanks for opening an issue!

**Comment by factorial52** [comment]
Too tired to add the github pull right now, but I'm pretty sure I got it figured and it's a really small patch. Here's a screenshot of '.../activity/DrawingActivity.kt'
![Screenshot_2021-04-12_23-19-55](https://user-images.githubusercontent.com/79954527/114492576-d697fb80-9be6-11eb-9b86-da29b0cdf865.png)

**Comment by TacoTheDank** [comment]
Awesome! I'll take a look.
